version: 2
jobs:
  build:
    docker:
      - image: fireshape/firedrake4tests:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run: . /home/firedrake/firedrake/bin/activate; export PYTHONPATH=$(pwd):$PYTHONPATH; mkdir test-results; pytest --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - run: . /home/firedrake/firedrake/bin/activate; export PYTHONPATH=$(pwd):$PYTHONPATH; make examples
      - run: . /home/firedrake/firedrake/bin/activate; export PYTHONPATH=$(pwd):$PYTHONPATH; make lint
