version: 2
jobs:
  build:
    docker:
      - image: fireshape/firedrake4tests:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: run lint
          command: |
            . /home/firedrake/firedrake/bin/activate
            export PYTHONPATH=$(pwd):$PYTHONPATH
            make lint
      - run:
          name: run tests
          command: |
            . /home/firedrake/firedrake/bin/activate
            export PYTHONPATH=$(pwd):$PYTHONPATH
            mkdir ./test-results
            pytest ./tests/test_L2tracking.py --junitxml=./test-results/junit.xml
      - store_test_results:
          path: ./test-results

      - run:
          name: run examples
          command: |
            . /home/firedrake/firedrake/bin/activate
            export PYTHONPATH=$(pwd):$PYTHONPATH
            make examples
