version: 2
jobs:
  build:
    docker:
      - image: fireshape/firedrake4tests:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run lint
          command: |
            . /home/firedrake/firedrake/bin/activate
            export PYTHONPATH=$(pwd):$PYTHONPATH
            make lint
      - run:
          name: run examples
          command: |
            . /home/firedrake/firedrake/bin/activate
            export PYTHONPATH=$(pwd):$PYTHONPATH
            make examples

  test:
    docker:
      - image: fireshape/firedrake4tests:latest

    working_directory: ~/repo

    parallelism: 10
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            . /home/firedrake/firedrake/bin/activate
            export PYTHONPATH=$(pwd):$PYTHONPATH
            mkdir ./test-results
            pip install pytest-circleci-parallelized
            pytest --circleci-parallelize --junitxml=./test-results/junit.xml
      - store_test_results:
          path: ./test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
