version: 2
jobs:
  build:
    docker:
      - image: fireshape/firedrake4tests:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install fireshape
          # Pass '--system-site-packages' so Firedrake is found
          command: |
            python3 -m venv --system-site-packages ~/venv
            . ~/venv/bin/activate
            python -m pip install -e .
            python -m pip list
      - run:
          name: run lint
          command: |
            . ~/venv/bin/activate
            python -m pip install flake8
            make lint
      - run:
          name: run examples
          command: |
            . ~/venv/bin/activate
            make examples

  test:
    docker:
      - image: fireshape/firedrake4tests:latest

    working_directory: ~/repo

    parallelism: 10
    steps:
      - checkout
      - run:
          name: run tests
          # Pass '--system-site-packages' so Firedrake is found
          command: |
            python3 -m venv --system-site-packages ~/venv
            . ~/venv/bin/activate
            python -m pip install -e .
            python -m pip install pytest-circleci-parallelized
            mkdir test-results
            python -m pytest --circleci-parallelize --junitxml=test-results/junit.xml
      - store_test_results:
          path: ./test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
