FROM firedrakeproject/firedrake-vanilla:latest
# keep as light as possible for CircleCI

MAINTAINER Alberto Paganini <admp1@le.ac.uk>

USER root
RUN apt-get update \
    && apt-get -y dist-upgrade \
    && apt-get -y install gmsh patchelf \
    && rm -rf /var/lib/apt/lists/*

# Now install fireshape
USER firedrake
RUN . /home/firedrake/firedrake/bin/activate; pip3 install wheel --upgrade
RUN . /home/firedrake/firedrake/bin/activate; pip3 install scipy
RUN . /home/firedrake/firedrake/bin/activate; pip3 install pip install pyroltrilinos
