FROM firedrakeproject/firedrake:latest
# build on fully fledged firedrake

MAINTAINER Alberto Paganini <admp1@le.ac.uk>

RUN apt-get update \
    && apt-get -y dist-upgrade \
    && apt-get -y install gmsh \
    && rm -rf /var/lib/apt/lists/*

# Now install fireshape
RUN pip install --verbose --src /opt \
        --editable git+https://github.com/fireshape/fireshape.git#egg=fireshape

