FROM firedrakeproject/firedrake-vanilla-default:latest
# keep as light as possible for CircleCI

MAINTAINER Alberto Paganini <admp1@le.ac.uk>

RUN apt-get update \
    && apt-get -y dist-upgrade \
    && apt-get -y install gmsh \
    && rm -rf /var/lib/apt/lists/*
