name: Publish Fireshape's Docker images

on:
  # Push to master or PR
  push:
    branches:
      - master
  pull_request:
  # build every week to stay up-to-date with firedrake
  schedule:
    - cron: '0 0 * * 1'

concurrency:
  # Cancels jobs running if new commits are pushed
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  #build: #eventually add job here if we want to also test installation

  docker:
    name: "Build Docker container"
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockerfile: [firedrake4tests, fireshape]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push firedrake4tests
        uses: docker/build-push-action@v4
        with:
          push: true
          no-cache: true
          file: docker/Dockerfile.${{ matrix.dockerfile }}
          tags: fireshape/${{ matrix.dockerfile }}:latest
