name: Publish Fireshape's Docker images

on:
  # Push to master or PR
  push:
    branches:
      - master
  pull_request:
  # build every week to stay up-to-date with firedrake
  schedule:
    - cron: '0 0 * * 0'

concurrency:
  # Cancels jobs running if new commits are pushed
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  #build: #eventually add job here if we want to also test installation

  docker_firedrake4tests:
    name: "Build firedrake4tests Docker container"
    # The type of runner that tests will run on
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push firedrake4tests
        uses: docker/build-push-action@v2
        with:
          push: true
          no-cache: true
          file: docker/Dockerfile.firedrake4tests
          tags: fireshape/firedrake4tests:latest

  docker_fireshape:
    name: "Build fireshape Docker container"
    # The type of runner that tests will run on
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push fireshape
        uses: docker/build-push-action@v2
        with:
          push: true
          no-cache: true
          file: docker/Dockerfile.fireshape
          tags: fireshape/fireshape:latest
